version: '3.8'

services:
    express-checkout:
        build:
            context: .
            dockerfile: ./docker-build/Dockerfile
        image: express-checkout
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
